name: publish ToolCenter

on:
  push:
    branches: [ 'master', 'main' ]
    paths:
      - "tools.json"
      - ".github/workflows/publish_toolcenter.yml"
  workflow_dispatch:

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: { }

jobs:
  trigger_deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Deploy Hook
        run: curl -X POST '${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}'
